-- Aftensmad — curated default recipes (visible to every user)

insert into public.recipes (owner, slug, name, category, link, image) values
  (null, 'andebryst', 'Andebryst', 'Hovedret', 'https://www.valdemarsro.dk/andebryst/', '/images/andebryst.jpg'),
  (null, 'ash-reshteh', 'Ash Reshteh', 'Hovedret', 'https://livsstil.tv2.dk/mad/opskrift/ash-reshteh-nudelsuppe', '/images/ash-reshteh.jpg'),
  (null, 'bagels', 'Bagels', 'Hovedret', 'https://www.nemlig.com/opskrifter/clubsandwich-med-chili-cheddar-bagel-miss-bagel-98002964', '/images/bagels.jpg'),
  (null, 'bagte-quesadillas-med-oksekoed', 'Bagte Quesadillas Med Oksekød', 'Hovedret', 'https://mummum.dk/bagte-quesadillas-med-oksekoed/', '/images/bagte-quesadillas-med-oksekoed.jpg'),
  (null, 'beef-wellington', 'Beef Wellington', 'Hovedret', 'https://www.valdemarsro.dk/beef-wellington/', '/images/beef-wellington.jpg'),
  (null, 'biksemad', 'Biksemad', 'Hovedret', 'https://www.valdemarsro.dk/biksemad-i-ovnen/', '/images/biksemad.jpg'),
  (null, 'blomkaalsris', 'Blomkålsris', 'Tilbehør', 'https://www.arla.dk/opskrifter/blomkalsris/', '/images/blomkaalsris.jpg'),
  (null, 'boller-i-karry', 'Boller i karry', 'Hovedret', 'https://madsvin.com/boller-i-karry-opskrift/', '/images/boller-i-karry.jpg'),
  (null, 'braendende-kaerlighed', 'Brændende Kærlighed', 'Hovedret', 'https://www.valdemarsro.dk/braendende-kaerlighed/', '/images/braendende-kaerlighed.jpg'),
  (null, 'burger', 'Burger', 'Hovedret', 'https://madensverden.dk/burger/', '/images/burger.jpg'),
  (null, 'boef-bearnaise', 'Bøf bearnaise', 'Hovedret', 'https://www.valdemarsro.dk/bearnaise/', '/images/boef-bearnaise.jpg'),
  (null, 'boefsandwich', 'Bøfsandwich', 'Hovedret', 'https://www.valdemarsro.dk/boefsandwich/', '/images/boefsandwich.jpg'),
  (null, 'chili-con-carne', 'Chili con carne', 'Hovedret', 'https://www.valdemarsro.dk/chili-con-carne/', '/images/chili-con-carne.jpg'),
  (null, 'chili-sin-carne', 'Chili sin carne', 'Hovedret', 'https://www.valdemarsro.dk/chili-sin-carne/', '/images/chili-sin-carne.jpg'),
  (null, 'cordon-bleu', 'Cordon bleu', 'Hovedret', 'https://www.valdemarsro.dk/cordon-bleu/', '/images/cordon-bleu.jpg'),
  (null, 'caesarsalat', 'Cæsarsalat', 'Hovedret', 'https://www.valdemarsro.dk/caesarsalat/', '/images/caesarsalat.jpg'),
  (null, 'dampede-blaamuslinger', 'Dampede blåmuslinger', 'Hovedret', 'https://madensverden.dk/dampede-blaamuslinger/', '/images/dampede-blaamuslinger.jpg'),
  (null, 'farserede-porrer', 'Farserede porrer', 'Hovedret', 'https://www.valdemarsro.dk/farserede-porrer/', '/images/farserede-porrer.jpg'),
  (null, 'feta-pasta', 'Feta Pasta', 'Hovedret', 'https://www.valdemarsro.dk/feta-pasta-med-tomat/', '/images/feta-pasta.jpg'),
  (null, 'fiskefrikadeller', 'Fiskefrikadeller', 'Hovedret', 'https://www.valdemarsro.dk/fiskefrikadeller/', '/images/fiskefrikadeller.jpg'),
  (null, 'flaeskesteg', 'Flæskesteg', 'Hovedret', 'https://www.valdemarsro.dk/flaeskesteg/', '/images/flaeskesteg.jpg'),
  (null, 'floedekartofler', 'Flødekartofler', 'Tilbehør', 'https://www.valdemarsro.dk/floedekartofler/', '/images/floedekartofler.jpg'),
  (null, 'forloren-hare', 'Forloren hare', 'Hovedret', 'https://www.valdemarsro.dk/forloren-hare/', '/images/forloren-hare.jpg'),
  (null, 'foraarsruller', 'Forårsruller', 'Hovedret', 'https://www.valdemarsro.dk/sproede-foraarsruller/', '/images/foraarsruller.jpg'),
  (null, 'frikadeller', 'Frikadeller', 'Hovedret', 'https://www.valdemarsro.dk/frikadeller/', '/images/frikadeller.jpg'),
  (null, 'frikadeller-med-stuvet-hvidkaal', 'Frikadeller med stuvet hvidkål', 'Hovedret', 'https://madogkaerlighed.dk/frikadeller-med-stuvet-hvidkaal/', '/images/frikadeller-med-stuvet-hvidkaal.jpg'),
  (null, 'fyldte-bagte-kartofler', 'Fyldte bagte kartofler', 'Hovedret', 'https://www.valdemarsro.dk/bagte-kartofler-med-fyld/', '/images/fyldte-bagte-kartofler.jpg'),
  (null, 'glaseret-skinke', 'Glaseret skinke', 'Hovedret', 'https://www.valdemarsro.dk/glaseret-skinke/', '/images/glaseret-skinke.jpg'),
  (null, 'grillspyd', 'Grillspyd', 'Hovedret', 'https://www.valdemarsro.dk/grillspyd-med-kylling/', '/images/grillspyd.jpg'),
  (null, 'groentsagslasagne', 'Grøntsagslasagne', 'Hovedret', 'https://www.valdemarsro.dk/vegetar-lasagne/', '/images/groentsagslasagne.jpg'),
  (null, 'gyros', 'Gyros', 'Hovedret', 'https://www.valdemarsro.dk/gyros/', '/images/gyros.jpg'),
  (null, 'hakkeboef-med-bloede-loeg', 'Hakkebøf med bløde løg', 'Hovedret', 'https://www.valdemarsro.dk/hakkeboef/', '/images/hakkeboef-med-bloede-loeg.jpg'),
  (null, 'helstegt-kylling', 'Helstegt kylling', 'Hovedret', 'https://www.valdemarsro.dk/helstegt-kylling/', '/images/helstegt-kylling.jpg'),
  (null, 'hjerter-i-floedesovs', 'Hjerter i flødesovs', 'Hovedret', 'https://www.google.com/search?q=hjerter+i+fl%C3%B8desovs+opskrift', ''),
  (null, 'hotdogs', 'Hotdogs', 'Hovedret', 'https://www.valdemarsro.dk/hotdogs/', '/images/hotdogs.jpg'),
  (null, 'hummerbisque', 'Hummerbisque', 'Forret', 'https://www.arla.dk/opskrifter/hummerbisque/', '/images/hummerbisque.jpg'),
  (null, 'indbagt-moerbrad', 'Indbagt mørbrad', 'Hovedret', 'https://www.valdemarsro.dk/pork-wellington/', '/images/indbagt-moerbrad.jpg'),
  (null, 'jomfruhummer', 'Jomfruhummer', 'Forret', 'https://www.valdemarsro.dk/jomfruhummer/', '/images/jomfruhummer.jpg'),
  (null, 'jordskokke-suppe', 'Jordskokke suppe', 'Hovedret', 'https://www.arla.dk/opskrifter/jordskokkesuppe/', '/images/jordskokke-suppe.jpg'),
  (null, 'kammuslinger', 'Kammuslinger', 'Forret', 'https://madensverden.dk/kammuslinger/', '/images/kammuslinger.jpg'),
  (null, 'karbonader', 'Karbonader', 'Hovedret', 'https://www.valdemarsro.dk/karbonader/', '/images/karbonader.jpg'),
  (null, 'kikaertegryde-med-linser-og-kokosmaelk', 'Kikærtegryde med linser og kokosmælk', 'Hovedret', 'https://www.valdemarsro.dk/kikaertegryde/', '/images/kikaertegryde-med-linser-og-kokosmaelk.jpg'),
  (null, 'koldskaal', 'Koldskål', 'Dessert', 'https://www.valdemarsro.dk/koldskaal/', '/images/koldskaal.jpg'),
  (null, 'koteletter-i-fad', 'Koteletter i fad', 'Hovedret', 'https://www.valdemarsro.dk/koteletter-i-fad/', '/images/koteletter-i-fad.jpg'),
  (null, 'kylling-i-cola', 'Kylling i cola', 'Hovedret', 'https://mummum.dk/kylling-i-cola/', '/images/kylling-i-cola.jpg'),
  (null, 'kylling-i-fad-med-pikant-og-groentsager', 'Kylling i fad med pikant og grøntsager', 'Hovedret', 'https://www.valdemarsro.dk/kylling-fad/', '/images/kylling-i-fad-med-pikant-og-groentsager.jpg'),
  (null, 'kylling-i-karry', 'Kylling i karry', 'Hovedret', 'https://www.valdemarsro.dk/kylling-karry/', '/images/kylling-i-karry.jpg'),
  (null, 'kyllingeschnitzel', 'Kyllingeschnitzel', 'Hovedret', 'https://madensverden.dk/kyllingeschnitzler/', '/images/kyllingeschnitzel.jpg'),
  (null, 'lakselasagne', 'Lakselasagne', 'Hovedret', 'https://www.valdemarsro.dk/lakselasagne/', '/images/lakselasagne.jpg'),
  (null, 'lakseroulade', 'Lakseroulade', 'Forret', 'https://www.valdemarsro.dk/lakseroulade-med-spinat/', '/images/lakseroulade.jpg'),
  (null, 'lammekrone', 'Lammekrone', 'Hovedret', 'https://www.valdemarsro.dk/lammekrone-ovnbagte-rosmarin-kartofler/', '/images/lammekrone.jpg'),
  (null, 'lammeskank', 'Lammeskank', 'Hovedret', 'https://madensverden.dk/lammeskank-roedvin-langtidsstegt/', '/images/lammeskank.jpg'),
  (null, 'lasagne', 'Lasagne', 'Hovedret', 'https://www.valdemarsro.dk/lasagne/', '/images/lasagne.jpg'),
  (null, 'lasagnette', 'Lasagnette', 'Hovedret', 'https://www.valdemarsro.dk/lasagnette/', '/images/lasagnette.jpg'),
  (null, 'madtaerte', 'Madtærte', 'Hovedret', 'https://www.valdemarsro.dk/porretaerte/', '/images/madtaerte.jpg'),
  (null, 'medisterpoelse', 'Medisterpølse', 'Hovedret', 'https://www.valdemarsro.dk/medister-med-kaal-og-aeble/', '/images/medisterpoelse.jpg'),
  (null, 'millionboef', 'Millionbøf', 'Hovedret', 'https://www.valdemarsro.dk/millionboef/', '/images/millionboef.jpg'),
  (null, 'moerbrad-a-la-creme', 'Mørbrad a la creme', 'Hovedret', 'https://www.arla.dk/opskrifter/morbradgryde/', '/images/moerbrad-a-la-creme.jpg'),
  (null, 'oksesteg', 'Oksesteg', 'Hovedret', 'https://www.arla.dk/opskrifter/gammeldags-oksesteg/', '/images/oksesteg.jpg'),
  (null, 'omelet', 'Omelet', 'Hovedret', 'https://www.valdemarsro.dk/omelet-med-skinke-og-ost/', '/images/omelet.jpg'),
  (null, 'orientalsk-risret-med-oksekoed', 'Orientalsk risret med oksekød', 'Hovedret', 'https://www.valdemarsro.dk/orientalsk-risret/', '/images/orientalsk-risret-med-oksekoed.jpg'),
  (null, 'osso-buco', 'Osso buco', 'Hovedret', 'https://www.valdemarsro.dk/osso-buco/', '/images/osso-buco.jpg'),
  (null, 'panang-karry-med-kylling', 'Panang karry med kylling', 'Hovedret', 'https://www.valdemarsro.dk/panang-karry-med-kylling/', '/images/panang-karry-med-kylling.jpg'),
  (null, 'pandekager', 'Pandekager', 'Dessert', 'https://www.valdemarsro.dk/pandekager/', '/images/pandekager.jpg'),
  (null, 'paprikagryde', 'Paprikagryde', 'Hovedret', 'https://www.valdemarsro.dk/paprikagryde/', '/images/paprikagryde.jpg'),
  (null, 'pariserboef', 'Pariserbøf', 'Hovedret', 'https://www.valdemarsro.dk/pariserbof/', '/images/pariserboef.jpg'),
  (null, 'pasta-i-peberfrugt-sauce', 'Pasta i Peberfrugt Sauce', 'Hovedret', 'https://mummum.dk/pastaret-i-peberfrugtsauce-med-moerbrad/', '/images/pasta-i-peberfrugt-sauce.jpg'),
  (null, 'pasta-med-pesto', 'Pasta med pesto', 'Hovedret', 'https://www.valdemarsro.dk/pesto-pasta/', '/images/pasta-med-pesto.jpg'),
  (null, 'pastasalat', 'Pastasalat', 'Hovedret', 'https://www.valdemarsro.dk/pastasalat-med-kylling-og-karrydressing/', '/images/pastasalat.jpg'),
  (null, 'pita', 'Pita', 'Hovedret', 'https://www.valdemarsro.dk/pita-med-kylling/', '/images/pita.jpg'),
  (null, 'pizza', 'Pizza', 'Hovedret', 'https://madensverden.dk/hjemmelavet-pizza/', '/images/pizza.jpg'),
  (null, 'pulled-pork', 'Pulled pork', 'Hovedret', 'https://www.valdemarsro.dk/carnitas-mexicansk-pulled-pork/', '/images/pulled-pork.jpg'),
  (null, 'ravioli-pasta', 'Ravioli Pasta', 'Hovedret', 'https://louiogbearnaisen.dk/2019/03/tortellini.html', '/images/ravioli-pasta.jpg'),
  (null, 'rejecocktail', 'Rejecocktail', 'Forret', 'https://www.valdemarsro.dk/rejecocktail/', '/images/rejecocktail.jpg'),
  (null, 'ribbenstegssandwich', 'Ribbenstegssandwich', 'Hovedret', 'https://madensverden.dk/ribbensandwich/', '/images/ribbenstegssandwich.jpg'),
  (null, 'risalamande', 'Risalamande', 'Dessert', 'https://www.valdemarsro.dk/risalamande/', '/images/risalamande.jpg'),
  (null, 'risengroed', 'Risengrød', 'Hovedret', 'https://www.valdemarsro.dk/risengroed/', '/images/risengroed.jpg'),
  (null, 'risotto', 'Risotto', 'Hovedret', 'https://www.valdemarsro.dk/citron-risotto/', '/images/risotto.jpg'),
  (null, 'roastbeef', 'Roastbeef', 'Hovedret', 'https://www.valdemarsro.dk/perfekt-tilberedt-roastbeef/', '/images/roastbeef.jpg'),
  (null, 'rullekebab', 'Rullekebab', 'Hovedret', 'https://www.valdemarsro.dk/nem-og-hurtig-kebab/', '/images/rullekebab.jpg'),
  (null, 'roedgroed-med-floede', 'Rødgrød med fløde', 'Dessert', 'https://www.valdemarsro.dk/roedgroed-med-floede/', '/images/roedgroed-med-floede.jpg'),
  (null, 'sesame-chicken', 'Sesame Chicken', 'Hovedret', 'https://curatedkitchenware.com/blogs/soupeduprecipes/sesame-chicken-1', '/images/sesame-chicken.jpg'),
  (null, 'skinkestang', 'Skinkestang', 'Hovedret', 'https://www.arla.dk/opskrifter/skinkestang/', '/images/skinkestang.jpg'),
  (null, 'skipperlabskovs', 'Skipperlabskovs', 'Hovedret', 'https://www.valdemarsro.dk/skipperlabskovs/', '/images/skipperlabskovs.jpg'),
  (null, 'sloppy-joes', 'Sloppy joes', 'Hovedret', 'https://madensverden.dk/sloppy-joes/', '/images/sloppy-joes.jpg'),
  (null, 'spaghetti-carbonara', 'Spaghetti Carbonara', 'Hovedret', 'https://meyers.dk/opskrifter/spaghetti-carbonara/p/72006/', '/images/spaghetti-carbonara.jpg'),
  (null, 'spaghetti-med-koedsovs', 'Spaghetti med kødsovs', 'Hovedret', 'https://www.valdemarsro.dk/koedsovs/', '/images/spaghetti-med-koedsovs.jpg'),
  (null, 'spareribs', 'Spareribs', 'Hovedret', 'https://www.valdemarsro.dk/spareribs-barbeque-marinade/', '/images/spareribs.jpg'),
  (null, 'stegt-fiskefilet', 'Stegt fiskefilet', 'Hovedret', 'https://www.valdemarsro.dk/fiskefilet-med-tatarsauce/', '/images/stegt-fiskefilet.jpg'),
  (null, 'stegt-flaesk-med-persillesovs', 'Stegt flæsk med persillesovs', 'Hovedret', 'https://www.valdemarsro.dk/stegt-flaesk-med-persillesauce-2/', '/images/stegt-flaesk-med-persillesovs.jpg'),
  (null, 'stegte-nudler', 'Stegte Nudler', 'Hovedret', 'https://www.dinneratthezoo.com/pan-fried-noodles/', '/images/stegte-nudler.jpg'),
  (null, 'stjerneskud', 'Stjerneskud', 'Hovedret', 'https://www.valdemarsro.dk/luksus-stjerneskud/', '/images/stjerneskud.jpg'),
  (null, 'sushi', 'Sushi', 'Hovedret', 'https://www.valdemarsro.dk/hjemmelavet-sushi/', '/images/sushi.jpg'),
  (null, 'svampesuppe', 'Svampesuppe', 'Forret', 'https://www.valdemarsro.dk/champignonsuppe/', '/images/svampesuppe.jpg'),
  (null, 'svensk-poelseret', 'Svensk Pølseret', 'Hovedret', 'https://www.valdemarsro.dk/svensk-poelseret/', '/images/svensk-poelseret.jpg'),
  (null, 'svenske-koedboller', 'Svenske kødboller', 'Hovedret', 'https://www.valdemarsro.dk/svenske-kottbullar-med-kartoffelmos-og-sauce/', '/images/svenske-koedboller.jpg'),
  (null, 'svinekaeber', 'Svinekæber', 'Hovedret', 'https://www.valdemarsro.dk/svinekaeber-braiserede-med-oel/', '/images/svinekaeber.jpg'),
  (null, 'tacos', 'Tacos', 'Hovedret', 'https://www.valdemarsro.dk/tacos/', '/images/tacos.jpg'),
  (null, 'tantanmen-ramen', 'Tantanmen Ramen', 'Hovedret', 'https://aaronandclaire.com/authentic-easy-tantanmen-at-home/', '/images/tantanmen-ramen.jpg'),
  (null, 'tarteletter', 'Tarteletter', 'Forret', 'https://www.valdemarsro.dk/tarteletter-hoens-asparges/', '/images/tarteletter.jpg'),
  (null, 'tatar', 'Tatar', 'Hovedret', 'https://www.valdemarsro.dk/tatar/', '/images/tatar.jpg'),
  (null, 'tortillas', 'Tortillas', 'Hovedret', 'https://www.valdemarsro.dk/nem-tortillas-med-krydret-oksekoed/', '/images/tortillas.jpg'),
  (null, 'tournedos-rossini', 'Tournedos', 'Hovedret', 'https://madensverden.dk/tournedos-af-kalvemoerbrad/', '/images/tournedos-rossini.jpg'),
  (null, 'tunsalat', 'Tunsalat', 'Hovedret', 'https://www.valdemarsro.dk/tunsalat/', '/images/tunsalat.jpg'),
  (null, 'varmroeget-laks', 'Varmrøget laks', 'Hovedret', 'https://www.valdemarsro.dk/wraps-med-varmroeget-laks/', '/images/varmroeget-laks.jpg'),
  (null, 'vegetar-enchiladas', 'Vegetar enchiladas', 'Hovedret', 'https://www.valdemarsro.dk/vegetar-enchiladas/', '/images/vegetar-enchiladas.jpg'),
  (null, 'vietnamesiske-sommerruller', 'Vietnamesiske sommerruller', 'Hovedret', 'https://www.valdemarsro.dk/sommerruller/', '/images/vietnamesiske-sommerruller.jpg'),
  (null, 'wienerschnitzel', 'Wienerschnitzel', 'Hovedret', 'https://www.valdemarsro.dk/wienerschnitzel/', '/images/wienerschnitzel.jpg'),
  (null, 'wok-med-nudler', 'Wok med nudler', 'Hovedret', 'https://www.valdemarsro.dk/wok/', '/images/wok-med-nudler.jpg')
on conflict do nothing;
